package Entities;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import enums.ReportType;

/**
 * Represents a report generated by the system.
 * 
 * A report can be of different types, such as subscribers report or time report.
 * It contains information about the reporting period, the generated content,
 * and associated weekly or time-based data.
 */
@SuppressWarnings("serial")
public class Report implements Serializable {

    /** Unique identifier for the report. */
    private int reportID;

    /** Type of the report. */
    private ReportType reportType;

    /** Start date of the reporting period. */
    private LocalDate startDate;

    /** End date of the reporting period. */
    private LocalDate endDate;

    /** Timestamp when the report was generated. */
    private LocalDateTime generatedAt;

    /** Content or description of the report. */
    private String content;

    /** List of weekly data, relevant for subscribers reports. */
    private List<WeekData> weekData;

    /** List of time-based data, relevant for time reports. */
    private List<TimeData> timeData;

    /**
     * Private constructor used internally to create a report.
     *
     * @param reportID the report ID
     * @param reportType the type of report
     * @param startDate start date of the report
     * @param endDate end date of the report
     * @param weekData list of weekly data (null if not applicable)
     * @param timeData list of time-based data (null if not applicable)
     * @param content the report content
     */
    private Report(int reportID, ReportType reportType, LocalDate startDate, LocalDate endDate, List<WeekData> weekData, List<TimeData> timeData, String content) {
        this.reportID = reportID;
        this.reportType = reportType;
        this.startDate = startDate;
        this.endDate = endDate;
        this.generatedAt = LocalDateTime.now();
        this.weekData = weekData;
        this.timeData = timeData;
        this.content = content;
    }

    /**
     * Creates a subscribers report.
     *
     * @param reportID the report ID
     * @param type the type of report
     * @param start start date of the reporting period
     * @param end end date of the reporting period
     * @param weekData weekly data for the report
     * @param content report content
     * @return a new Report object for subscribers
     */
    public static Report createSubscribersReport(int reportID, ReportType type, LocalDate start, LocalDate end, List<WeekData> weekData, String content) {
        return new Report(reportID, type, start, end, weekData, null, content);
    }

    /**
     * Creates a time-based report.
     *
     * @param reportID the report ID
     * @param type the type of report
     * @param start start date of the reporting period
     * @param end end date of the reporting period
     * @param timeData time-based data for the report
     * @param content report content
     * @return a new Report object for time-based data
     */
    public static Report createTimeReport(int reportID, ReportType type, LocalDate start, LocalDate end, List<TimeData> timeData, String content) {
        return new Report(reportID, type, start, end, null, timeData, content);
    }

    /** Returns the report ID. */
    public int getReportID() { return reportID; }

    /** Returns the type of the report. */
    public ReportType getReportType() { return reportType; }

    /** Returns the start date of the report period. */
    public LocalDate getStartDate() { return startDate; }

    /** Returns the end date of the report period. */
    public LocalDate getEndDate() { return endDate; }

    /** Returns the timestamp when the report was generated. */
    public LocalDateTime getGeneratedAt() { return generatedAt; }

    /** Returns the content or description of the report. */
    public String getContent() { return content; }

    /** Returns the weekly data of the report, if any. */
    public List<WeekData> getWeekData() { return weekData; }

    /** Returns the time-based data of the report, if any. */
    public List<TimeData> getTimeData() { return timeData; }
}
